services:
    app:
        build: .
        restart: unless-stopped
        ports:
            - "8000:8000"
        env_file:
            - .env
        environment:
            - PYTHONUNBUFFERED=1
            - MYSQL_HOST=mysql
        depends_on:
            - database

    database:
        image: mariadb:latest
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
