services:
    app:
        build: .
        restart: unless-stopped
        ports:
            - "8000:8000"
        env_file:
            - .env
        environment:
            - PYTHONUNBUFFERED=1
            - MYSQL_HOST=mysql
        depends_on:
            - database

    database:
        image: mariadb:latest
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
